# Generated by Django 5.0.7 on 2024-08-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='Fecha_Now',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
